# Generated by Django 4.2 on 2025-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('skill_level', models.CharField(max_length=100)),
                ('materials_needed', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
