# Generated by Django 5.1.7 on 2025-03-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Blankets', 'Blankets'), ('Cardigans', 'Cardigans'), ('Amigurumi', 'Amigurumi'), ('Scarves', 'Scarves'), ('Hats', 'Hats')], default='Blankets', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
