# Generated by Django 5.1.7 on 2025-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0002_project_category_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pattern',
            field=models.FileField(blank=True, null=True, upload_to='patterns/'),
        ),
    ]
