# Generated by Django 5.1.7 on 2025-04-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0003_project_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Blankets', 'Blankets'), ('Cardigans', 'Cardigans'), ('Amigurumi', 'Amigurumi'), ('Scarves', 'Scarves'), ('Hats', 'Hats')], max_length=50),
        ),
    ]
