# Generated by Django 4.2 on 2025-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crochet', '0005_alter_project_options_alter_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Blankets', 'Blankets'), ('Cardigans', 'Cardigans'), ('Amigurumi', 'Amigurumi'), ('Scarves', 'Scarves'), ('Hats', 'Hats'), ('Dishcloths', 'Dishcloths')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default_image.jpg', upload_to='projects/images/'),
            preserve_default=False,
        ),
    ]
